https://github.com/ZFTurbo/Weighted-Boxes-Fusion
https://codechina.csdn.net/WXL11221/Weighted-Boxes-Fusion/-/tree/master/examples

https://github.com/ZFTurbo/Weighted-Boxes-Fusion/blob/master/ensemble_boxes/ensemble_boxes_wbf.py

Artigo:
https://www.sciencedirect.com/science/article/pii/S0262885621000226?via%3Dihub

https://medium.com/analytics-vidhya/weighted-boxes-fusion-86fad2c6be16

faster nms: https://www.pyimagesearch.com/2015/02/16/faster-non-maximum-suppression-python/

In [1]:
#!pip install ensemble-boxes

In [1]:
from ensemble_boxes import *

In [2]:
boxes_list = [[
    [0.00, 0.51, 0.81, 0.91],
    [0.10, 0.31, 0.71, 0.61],
    [0.01, 0.32, 0.83, 0.93],
    [0.02, 0.53, 0.11, 0.94],
    [0.03, 0.24, 0.12, 0.35],
],[
    [0.04, 0.56, 0.84, 0.92],
    [0.12, 0.33, 0.72, 0.64],
    [0.38, 0.66, 0.79, 0.95],
    [0.08, 0.49, 0.21, 0.89],
]]

In [3]:
scores_list = [[0.9, 0.8, 0.2, 0.4, 0.7], [0.5, 0.8, 0.7, 0.3]]
labels_list = [[0, 1, 0, 1, 1], [1, 1, 1, 0]]
weights = [2, 1]

iou_thr = 0.5
skip_box_thr = 0.0001
sigma = 0.1

In [4]:
boxes, scores, labels = nms(boxes_list, scores_list, labels_list, weights=weights, iou_thr=iou_thr)

print(boxes)
print(scores)
print(labels)

[[0.   0.51 0.81 0.91]
 [0.08 0.49 0.21 0.89]
 [0.1  0.31 0.71 0.61]
 [0.03 0.24 0.12 0.35]
 [0.02 0.53 0.11 0.94]
 [0.38 0.66 0.79 0.95]
 [0.04 0.56 0.84 0.92]]
[0.6        0.1        0.53333333 0.46666667 0.26666667 0.23333333
 0.16666667]
[0 0 1 1 1 1 1]


In [10]:
boxes, scores, labels = soft_nms(boxes_list, scores_list, labels_list, weights=weights, iou_thr=iou_thr, sigma=sigma, thresh=skip_box_thr)

print(boxes)
print(scores)
print(labels)

[[0.   0.51 0.81 0.91]
 [0.08 0.49 0.21 0.89]
 [0.01 0.32 0.83 0.93]
 [0.1  0.31 0.71 0.61]
 [0.03 0.24 0.12 0.35]
 [0.02 0.53 0.11 0.94]
 [0.38 0.66 0.79 0.95]
 [0.04 0.56 0.84 0.92]
 [0.12 0.33 0.72 0.64]]
[0.4        0.03333333 0.08888889 0.35555556 0.31111111 0.17777778
 0.07777778 0.05555556 0.08888889]
[0 0 0 1 1 1 1 1 1]


In [11]:
boxes, scores, labels = non_maximum_weighted(boxes_list, scores_list, labels_list, weights=weights, iou_thr=iou_thr, skip_box_thr=skip_box_thr)

print(boxes)
print(scores)
print(labels)

[[0.00123605 0.48651513 0.8124721  0.91247207]
 [0.10184006 0.31184006 0.71092004 0.61276007]
 [0.03       0.23999998 0.11999999 0.35      ]
 [0.02       0.53000003 0.11       0.94      ]
 [0.38       0.65999997 0.78999996 0.95      ]
 [0.04       0.56       0.84       0.91999996]
 [0.08       0.49       0.21       0.8899999 ]]
[0.4        0.35555556 0.31111112 0.17777778 0.03888889 0.02777778
 0.01666667]
[0. 1. 1. 1. 1. 1. 0.]


In [12]:
boxes, scores, labels = weighted_boxes_fusion(boxes_list, scores_list, labels_list, weights=weights, iou_thr=iou_thr, skip_box_thr=skip_box_thr)

print(boxes)
print(scores)
print(labels)

[[0.00181818 0.47545454 0.81363636 0.91363633]
 [0.10222223 0.31222221 0.71111113 0.61333328]
 [0.03       0.24       0.12       0.35      ]
 [0.02       0.53       0.11       0.94      ]
 [0.38       0.66       0.79       0.95      ]
 [0.04       0.56       0.84       0.92      ]
 [0.08       0.49       0.21       0.89      ]]
[0.32592592 0.26666668 0.20740741 0.11851852 0.02592593 0.01851852
 0.01111111]
[0. 1. 1. 1. 1. 1. 0.]


In [9]:
filename = 'T'

In [10]:
for i in range(len(boxes_list)):
    with open(filename + str(i) + '.txt', "w") as f:
        for j in range(len(boxes_list[i])):        
            f.write(str(boxes_list[i][j]) + '\n')                        
    f.close()

In [22]:
# Converte string para lista
def Convert_str_to_float(string):
    li = list(string.split(", "))
    return li

In [44]:
import re
def convert_df_lista_int(str1):    
    str1 = re.sub(r"[\([{})\]]", "", str1) # remove os caracteres da string
    #str1 = (str1.replace('.0', '')) # substirui a casa decimal .0 por vazio, tornando a string no formato int
    str1 = list(str1.split(", "))    
    str1 = [(float(i)) for i in str1] # convert os valores para inteiro e depois string    
    return str1

In [45]:
path = os.getcwd()
print(path)

import numpy as np

l = []

import glob
for filename in glob.glob('*.txt'):
    with open(os.path.join(os.getcwd(), filename), 'r') as f: # open in readonly mode        
        print(filename)
        
        m = []
        for line in f:
            if line: #avoid blank lines
                ll = convert_df_lista_int(line)
                #print(ll)   
            m.append(ll)        
        
    print(m)
        

/home/karem/Artigo_Periodico
T0.txt
[[0.0, 0.51, 0.81, 0.91], [0.1, 0.31, 0.71, 0.61], [0.01, 0.32, 0.83, 0.93], [0.02, 0.53, 0.11, 0.94], [0.03, 0.24, 0.12, 0.35]]
T1.txt
[[0.04, 0.56, 0.84, 0.92], [0.12, 0.33, 0.72, 0.64], [0.38, 0.66, 0.79, 0.95], [0.08, 0.49, 0.21, 0.89]]


In [47]:
m[1]

[0.12, 0.33, 0.72, 0.64]